
CREATE DATABASE IF NOT EXISTS MONEY_TRANSFER_DW;


CREATE SCHEMA IF NOT EXISTS MONEY_TRANSFER_DW.ANALYTICS;


CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH 
  WITH WAREHOUSE_SIZE = 'XSMALL' 
  AUTO_SUSPEND = 300 
  AUTO_RESUME = TRUE;


USE DATABASE MONEY_TRANSFER_DW;
USE SCHEMA ANALYTICS;
USE WAREHOUSE COMPUTE_WH;


CREATE OR REPLACE FILE FORMAT csv_file_format
  TYPE = 'CSV'
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  NULL_IF = ('NULL', 'null')
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  EMPTY_FIELD_AS_NULL = TRUE;

CREATE OR REPLACE STAGE transactions_stage
  FILE_FORMAT = csv_file_format;
