USE DATABASE MONEY_TRANSFER_DW;
USE SCHEMA ANALYTICS;

-- Fact Transactions Table
CREATE OR REPLACE TABLE FACT_TRANSACTIONS (
    transaction_key NUMBER IDENTITY(1,1) PRIMARY KEY,
    account_from_key NUMBER FOREIGN KEY REFERENCES DIM_ACCOUNT(account_key),
    account_to_key NUMBER FOREIGN KEY REFERENCES DIM_ACCOUNT(account_key),
    date_key NUMBER FOREIGN KEY REFERENCES DIM_DATE(date_key),
    amount DECIMAL(18,2) NOT NULL,
    status VARCHAR(20) NOT NULL
);
